#pragma once

#define NOH_MACRO_VAL(str) #str
#define NOH_MACRO_TOSTRING(str) NOH_MACRO_VAL(str)

#define NOH_VERSION_MAJOR          1
#define NOH_VERSION_MINOR          0
#define NOH_VERSION_PATCH          0
#define NOH_VERSION_PRERELEASE_TAG ""

#define NOH_VERSION                ((NOH_VERSION_MAJOR * 100 * 100) + (NOH_VERSION_MINOR * 100) + (NOH_VERSION_PATCH))
#define NOH_VERSION_SHORT_STRING   NOH_MACRO_TOSTRING(NOH_VERSION_MAJOR) "." NOH_MACRO_TOSTRING(NOH_VERSION_MINOR) "." NOH_MACRO_TOSTRING(NOH_VERSION_PATCH)
#define NOH_VERSION_STRING         NOH_VERSION_SHORT_STRING NOH_VERSION_PRERELEASE_TAG
